name: sf3dmodels

channels:
    - astropy
    - conda-forge

dependencies:
    - astropy=2.0.9
#    - cython
#    - matplotlib
#    - numpy
    - sphinx-astropy
#    - pandas
#    - pip:
#       - dependency_from_pip
