name: sf3dmodels

channels:
    - astropy

dependencies:
    - astropy
    - Cython
    - matplotlib
    - numpy
    - pandas=0.23.3=py27hf8a1672_1
    - sphinx-astropy
#   - pip:
#       - dependency_from_pip
