name: sf3dmodels

channels:
    - astropy

dependencies:
    - astropy
    - Cython
    - matplotlib
    - numpy
    - pandas
    - pip:
      - "git+https://github.com/sphinx-gallery/sphinx-gallery.git"
